use computerdb;

describe computer;
select * from computer;
insert into computerdb.computer values(1, 'Intel', 'desktop', 6, 'Corei7');
insert into computerdb.computer values(2, 'Macbook Pro', 'laptop', 1, 'Corei10');
update computer set name = "Samsung" where id = 1;
update computer set name = "Acer", type = "ipad", amount = 20 where id = 1;
select * from computer where name = "Macbook Pro";
select * from computer where name like "M%";
select * from computer where name like "%M";
insert into computerdb.computer values(3, 'Acer', 'laptop', 20, 'Corei9');
delete from computer where id=3;
delete from computer where name="Acer" and type="ipad";
insert into computerdb.computer values(3, 'Acer', 'laptop', 20, 'Corei9');
insert into computerdb.computer values(1, 'Acer', 'laptop', 10, 'Corei8');
delete from computer where name="Acer" and type="laptop";
delete from computer;
insert into computerdb.computer values(2, 'BigFlop Mark II', 'gameover', 20, 'Brain 456');
insert into computerdb.computer values(7, 'Cera 2400', 'laptop', 5, 'Selenium II');
insert into computerdb.computer values(6, 'MaxEffect 2000', 'supercomputer', 100, 'MotorOle');
insert into computerdb.computer values(1, 'GameDelux', 'embedded', 7, 'PiTron 3');
insert into computerdb.computer values(5, 'King 3000', 'server', 10, 'MinPower');
insert into computerdb.computer values(3, 'Xunil 4.7', 'tabletop', 1, 'BNE');
insert into computerdb.computer values(4, 'Beast II', 'pocket Computer', 150, 'X-Force');
select * from computer;
select id, amount, type from computer;
select * from computer where processor="Brain 456";
select * from computer where name="GameDelux";
select * from computer where name="BigFlop Mark II";
update computer set type = "pocket computer", amount = 15 where id = 1;
update computer set amount = 13, processor = "Brain 456", name = "MaxEffect 2000" where id = 3;
update computer set type = "laptop", amount = 10, name ="BigFlop Mark II" where id = 4;
delete from computer where id = 5;
delete from computer where id = 2;
delete from computer where name = "BigFlop Mark II";
delete from computer where amount = 7 or processor = "Brain 456";
delete from computer where name = "BigFlop MArk II" or amount = 100 or processor = "X-Force";