use superherodb;

select * from superhero;
select name, heroID, costume from superhero;
select name,heroID,costume from superhero order by name;
select name,heroID,costume from superhero order by name desc;
select heroID,costume from superhero order by name desc;
select heroID,costume from superhero order by name asc;
select heroID,costume from superhero order by name;
select heroID, name, yearOfBirth from superhero order by yearOfBirth;
select heroID, name, yearOfBirth from superhero order by yearOfBirth desc;
select * from superhero where name='Rustman';
select * from superhero where name='Rustman' or name='DataMaster';
select * from superhero where name='Rustman'and name='DataMaster';
select * from superhero where yearOfBirth>=2000;
select * from superhero where yearOfBirth<=1990;
select heroId, name, costume from superhero where costume='red';
select name,gear from superhero where name='SuperGenious';
select name, yearOfBirth from superhero where yearOfBirth>=1990 and yearOfBirth<=2000;
select name, yearOfBirth from superhero where yearOfBirth>=1930 and yearOfBirth<=1990;
select name,yearOfBirth from superhero where yearOfBirth between 1930 and 1990;
select name from superhero where name like 'S%';
select name from superhero where name like '%n';
select name from superhero where name like '%er%';
select gear from superhero where gear like '_e%';
select * from superhero where name like 's%' or name like 'S%';
select * from superhero where lower(name)='superMoron';
select * from superhero where upper(name)='SUPERMORON';
select * from superhero where lower(name)=lower('SUPERMORON');
update superhero set name='super%Moron' where heroID=1;
select * from superhero where lower(name)=lower('SUPER%MORON');
select * from superhero where name like '%\%%';
select * from superhero where name in ('Rustman','DataMaster');
select * from superhero where name not in ('Rustman','DataMaster');
select * from superhero where name not in ('Rustman','DataMaster') and yearOfBirth<2000;
select min(yearOfBirth) as oldest, max(yearOfBirth) as youngest from superhero;
select year(current_date)-min(yearOfBirth) as age from superhero;
select year(current_date)-max(yearOfBirth) as age from superhero;
select name from superhero where yearOfBirth=(select min(yearOfBirth) from superhero);
select name,year(current_date)-yearOfBirth as age from superhero;
select name,year(current_date)-yearOfBirth as age from superhero order by age;
select name,year(current_date)-yearOfBirth as age from superhero order by age desc;

insert into superhero values(8, 'Data_Master','Cape','red',1899);
insert into superhero values(9, 'DataXMaster','Capex','redx',1999);
select * from superhero where name like 'Data_Master';
select * from superhero where name like 'Data\_Master';
update superhero set name='Super_QL' where heroID=5;
select * from superhero where name like '%\_%';

update superhero set gear='JumpBoots', name='SuperMoron' where heroID=3;
select * from superhero;
update superhero set gear='HelmeT', costume='blue' where heroID=4;
select * from superhero where heroID=4;
update superhero set gear='JumpBoots', yearOfBirth=1930, name='SuperMoron' where heroID=6;
select * from superhero where heroID=6;
update superhero set yearOfBirth=1960, costume='blue', name='Lightning' where heroID=2;
select * from superhero where heroID=2;

delete from superhero where heroID=5;
select * from superhero;
delete from superhero where heroID=2;
select * from superhero;
delete from superhero where yearOfBirth=2017;
select * from superhero;
select * from superhero where gear='HelmeT' or name='SuperQL';
delete from superhero where gear='HelmeT' or name='SuperQL';
delete from superhero where name='super%Moron' or gear='Capex';
select * from superhero;
delete from superhero where name like 'Super%';
select * from superhero;
insert into superhero values(1,'Rustman','Cape','blue',1990);
select * from superhero;
select * from superhero where name='Rustman' and costume='green';
select gear from superhero where name='Rustman' and costume='green';
select gear from superhero where name='Rustman' or costume='green';
select * from superhero where name='Rustman' or gear='Cape';
select * from superhero where name='Data_Master' or gear='Cape';
select * from superhero where name='Data_Master' and gear='Cape';
delete from superhero where name='Data_Master' or gear='Cape';
select * from superhero;
delete from superhero;
